using System;
using System.Collections.Generic;
using System.Text;

public enum MaterialType : int
{
    STONE = 0,
    BONE = 1,
    SMALL_HAMMER = 1001,
    TOOL_STONE_PICKAXE = 51,
    TOOL_IRON_PICKAXE = 50,
    TOOL_STEEL_PICKAXE = 52,
    BONE_CLUP_WEAPON = 200,
    WOODEN_CLUP_WEAPON = 201,
    GUARD_SWORD_WEAPON = 202,
    SMALLAXE_WEAPON = 203,
    KNIGHT_SWORD_WEAPON = 204,
    PEASANT_HELMET = 600,
    PEASANT_CLOTHING_ARMOR = 601,
    LEATHER_HELMET = 620,
    LEATHER_JACKET_ARMOR = 621,
    CHAINMAIL_HELMET = 800,
    CHAINMAIL_LIGHT_ARMOR = 801,
    CATAPHRACT_ARMOR = 901,
    CATAPHRACT_HELMET = 902,
    ELITE_KNIGHT_HELMET = 903,
    ELITE_GUARD_ARMOR = 904,
   
}